<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SUN-HSINGH2" ignored="0" name="suiteA" tests="5" failures="3" timestamp="2022-06-26T20:23:41 EDT" time="0.054" errors="0">
  <testcase name="useDataProvider" time="0.008" classname="SuiteA.PracticeDataProvider">
    <failure type="java.lang.AssertionError" message="Testcase is failing here">
      <![CDATA[java.lang.AssertionError: Testcase is failing here
at SuiteA.PracticeDataProvider.useDataProvider(PracticeDataProvider.java:15)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- useDataProvider -->
  <testcase name="useDataProvider" time="0.001" classname="SuiteA.PracticeDataProvider">
    <failure type="java.lang.AssertionError" message="Testcase is failing here">
      <![CDATA[java.lang.AssertionError: Testcase is failing here
at SuiteA.PracticeDataProvider.useDataProvider(PracticeDataProvider.java:15)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- useDataProvider -->
  <testcase name="useDataProvider" time="0.001" classname="SuiteA.PracticeDataProvider">
    <failure type="java.lang.AssertionError" message="Testcase is failing here">
      <![CDATA[java.lang.AssertionError: Testcase is failing here
at SuiteA.PracticeDataProvider.useDataProvider(PracticeDataProvider.java:15)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- useDataProvider -->
  <testcase name="InstDataProvider" time="0.001" classname="SuiteA.PracticeDataProvider"/>
  <testcase name="InstDataProvider" time="0.001" classname="SuiteA.PracticeDataProvider"/>
</testsuite> <!-- suiteA -->
